# schema shows the data column names and type, used for data validation to ensure data is in correct format.

COLUMNS:
  id: int64
  carat: float64
  cut: object
  color: object
  clarity: object
  depth: float64
  table: float64
  x: float64
  y: float64
  z: float64

TARGET_COLUMN:
  price: int64
